# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(672, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topButtonFrame = QtWidgets.QFrame(self.centralwidget)
        self.topButtonFrame.setObjectName("topButtonFrame")
        self.formLayout = QtWidgets.QFormLayout(self.topButtonFrame)
        self.formLayout.setObjectName("formLayout")
        self.addButton = QtWidgets.QPushButton(self.topButtonFrame)
        self.addButton.setObjectName("addButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.addButton)
        self.practiceButton = QtWidgets.QPushButton(self.topButtonFrame)
        self.practiceButton.setObjectName("practiceButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.practiceButton)
        self.verticalLayout.addWidget(self.topButtonFrame, 0, QtCore.Qt.AlignHCenter)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(400, 400))
        self.frame.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.itemBox = QtWidgets.QTextEdit(self.frame)
        self.itemBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.itemBox.setStyleSheet("overflow:scroll")
        self.itemBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.itemBox.setObjectName("itemBox")
        self.gridLayout.addWidget(self.itemBox, 1, 1, 1, 3)
        self.cancelImageButton = QtWidgets.QPushButton(self.frame)
        self.cancelImageButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.cancelImageButton.setObjectName("cancelImageButton")
        self.gridLayout.addWidget(self.cancelImageButton, 4, 0, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.notesBox = QtWidgets.QTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notesBox.sizePolicy().hasHeightForWidth())
        self.notesBox.setSizePolicy(sizePolicy)
        self.notesBox.setMaximumSize(QtCore.QSize(16777215, 200))
        self.notesBox.setAcceptDrops(True)
        self.notesBox.setObjectName("notesBox")
        self.gridLayout.addWidget(self.notesBox, 3, 1, 1, 3)
        self.notesLabel = QtWidgets.QLabel(self.frame)
        self.notesLabel.setObjectName("notesLabel")
        self.gridLayout.addWidget(self.notesLabel, 3, 0, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.cancelButton = QtWidgets.QPushButton(self.frame)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 0, 3, 1, 1, QtCore.Qt.AlignLeft)
        self.imageBox = QtWidgets.QWidget(self.frame)
        self.imageBox.setMinimumSize(QtCore.QSize(200, 200))
        self.imageBox.setMaximumSize(QtCore.QSize(150, 150))
        self.imageBox.setAcceptDrops(True)
        self.imageBox.setAccessibleName("")
        self.imageBox.setAutoFillBackground(False)
        self.imageBox.setStyleSheet("border: 4px dashed #aaa;")
        self.imageBox.setObjectName("imageBox")
        self.gridLayout.addWidget(self.imageBox, 4, 2, 1, 2, QtCore.Qt.AlignVCenter)
        self.itemLabel = QtWidgets.QLabel(self.frame)
        self.itemLabel.setObjectName("itemLabel")
        self.gridLayout.addWidget(self.itemLabel, 1, 0, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.addImageButton = QtWidgets.QPushButton(self.frame)
        self.addImageButton.setAutoDefault(False)
        self.addImageButton.setDefault(False)
        self.addImageButton.setFlat(False)
        self.addImageButton.setObjectName("addImageButton")
        self.gridLayout.addWidget(self.addImageButton, 4, 1, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.completeButton = QtWidgets.QPushButton(self.frame)
        self.completeButton.setObjectName("completeButton")
        self.gridLayout.addWidget(self.completeButton, 0, 2, 1, 1, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.addButton, self.practiceButton)
        MainWindow.setTabOrder(self.practiceButton, self.completeButton)
        MainWindow.setTabOrder(self.completeButton, self.cancelButton)
        MainWindow.setTabOrder(self.cancelButton, self.itemBox)
        MainWindow.setTabOrder(self.itemBox, self.notesBox)
        MainWindow.setTabOrder(self.notesBox, self.cancelImageButton)
        MainWindow.setTabOrder(self.cancelImageButton, self.addImageButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.practiceButton.setText(_translate("MainWindow", "Practice"))
        self.cancelImageButton.setText(_translate("MainWindow", "x"))
        self.notesLabel.setText(_translate("MainWindow", "Notes"))
        self.cancelButton.setText(_translate("MainWindow", "Cancel"))
        self.itemLabel.setText(_translate("MainWindow", "Item"))
        self.addImageButton.setText(_translate("MainWindow", "+  image"))
        self.completeButton.setText(_translate("MainWindow", "Complete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
